cart/urls.py
from django.contrib import admin
from django.urls import path, include
from cart import views
app_name ="cart"

urlpatterns = [
    path('cart/<n>',views.cart, name='cart'),
    path('cartview',views.cartview, name='cartview'),
    path('remove/<str:n>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/decrement/<str:n>/', views.decrement_cart, name='decrement_cart'),
    path('orderform',views.orderform, name='orderform'),



]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('', include('cart.urls')),
    path('/search',include('search.urls')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name='search'
urlpatterns = [
    path('search',views.search,name="search"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('product/<p>',views.product,name='product'),
    path('detail/<p>',views.detail,name='detail'),
    path('register',views.register,name='register'),
    path('login', views.userlogin,name="userlogin"),
    path('logout', views.user_logout,name="user_logout"),
]

cart/models.py
from os import name

from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.Product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    address = models.TextField()
    phone = models.IntegerField()
    order_status = models.BooleanField(default='pending')
    delivery_status = models.BooleanField(default='pending')
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return self.acctnum

search/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="Category",null=True,blank=True)
    def __str__(self):
        return self.name
class Product(models.Model):
    name = models.CharField(max_length=30)
    desc = models.TextField(default="")
    image = models.ImageField(upload_to='product', null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def str(self):
        return self.name

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from shop.models import Product
from cart.models import Cart,Account

from cart.models import Account


def cartview(request):
    total=0
    u=request.user
    cart=Cart.objects.filter(user=u)
    for i in cart:
        total+=i.quantity*i.product.price
    return render(request, 'cart.html',{'c':cart,'total':total})
@login_required
# Create your views here.
def cart(request,n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u,product=p)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
            cart.save()
    except:
        if(p.stock>0):
            cart = Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
    return redirect('cart:cartview')
def remove_from_cart(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart_item = Cart.objects.get(user=u, product=p)
        cart_item.delete()
    except Cart.DoesNotExist:
        # Handle the case where the item is not in the cart
        raise Http404("Item not found in the cart")

    return redirect('cart:cartview')
def decrement_cart(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)

        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()

    except Cart.DoesNotExist:
        pass

    return redirect('cart:cartview')
def orderform (request):
    if request.method=="POST":
        a=request.POST['a']
        ph=request.POST['ph']
        an=request.POST['an']

        u=request.user
        cart=Cart.objects.filter(user=u)

        total=0
        for i in cart:
            total+=i.quantity*i.product.price


        try:
            ac=Account.objects.get(accnum=an)
            if(ac.amount >= total):
                ac=amount=ac.amount-total
                ac.save()
                return HttpResponse('Ordered')
            else:
                return HttpResponse('insufficent')

        except:
            pass
        return HttpResponse(total)



    return render(request, 'orderform.html')

search/views.py
from django.shortcuts import render
from django.db.models import Q

from shop.models import Product


def search(request):
    b=None
    q=""
    if (request.method=="POST"):
        q=request.POST['q']
        if q:
            b=Product.objects.filter(Q(name__icontains=q) | Q(desc__icontains=q))
            return render(request,'search.html',{'q':q,'b':b})

shop/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from shop.models import Category, Product
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth import login, authenticate , logout
from django.contrib.auth.decorators import login_required

# Create your views here.


def allcategories(request):
    k = Category.objects.all()
    return render(request, 'category.html', context={'c': k})
def product(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request, 'product.html', context={'c': c,'p':p})
def detail(request,p):
    p=Product.objects.get(name=p)
    return render(request, 'detail.html', context={'p': p})

def register(request):
    if (request.method == 'POST'):
        u = request.POST['u']
        q = request.POST['q']
        r = request.POST['r']
        f = request.POST['f']
        l = request.POST['l']
        e = request.POST['e']
        if(q==r):
            b = User.objects.create_user(username=u, password=q, first_name=f, last_name=l,email=e)
            b.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("pass same")
    return render(request, 'register.html')

def userlogin(request):
    if (request.method == 'POST'):
        u = request.POST['u']
        p = request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            return HttpResponse("Invalid credentials")
    return render(request, 'login.html')
@login_required
def user_logout(request):
    logout(request)
    return redirect('shop:userlogin')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

     <!--bootstrap-->

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href='{% static "css/style.css" %}'>

    <!--    google font-->

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

     <!-- icon -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
<header><center>
    <img src="{% static 'images/0111.png' %}" height="140px" width="200px">
</center></header>

           <!--navbar-->

<nav class="navbar navbar-expand-lg navbar-light bg-warning mt-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="">Home</a>
        </li>



          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:product' i.name %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:user_logout' %}">logout</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup class="ms-2">{{count}}</sup></a>
          </li>
          {% else %}
<li class="nav-item">
              <a class="nav-link" href="{% url 'shop:register' %}">Register</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:userlogin' %}">login</a>
          </li>
{% endif %}
      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}

{% block category %}

{% endblock %}

<footer class="fixed-bottom bg-warning text-center">
  <div class="container p-3">
    <section class="mb-3">
      KURIKKAL HOLDINGS All Rights Reserved
    </section>
  </div>
</footer>


</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="container mt-5" style="margin-bottom :100px;">
        <div class="row  justify-content-center">
            <h1>Shopping Cart</h1>
            <br>

            <div class="col-9">
                <table class="table table-bordered">
                    <tr>
                        <th colspan="5">Cart-Items</th>
                    </tr>
                    {% for i in c %}
                        <tr>
                            <td>
                                <img src="{{ i.product.image.url }}" height="200px" width="200px">

                            </td>
                            <td>
                                <p>{{i.product.name}}</p>
                            </td>
                            <td>
                                <h6>Productid:{{i.product.id}}</h6>
                                <h6>Unit Price:{{i.product.price}}</h6>
                                <h6>Quantity: {{i.quantity}}*{{i.product.price}}</h6>
                                <h6>stock: {{i.product.stock}}-{{i.quantity}}</h6>


                            </td>
                            <td>Subtotal:{{i.subtotal}}</td>
                                                <td>
                                                    {% if i.quantity < i.product.stock %}
                                <a href="{% url 'cart:cart' i.product.name %}"><i class="fa-solid fa-circle-plus"></i></a>
                                <a href="{% url 'cart:decrement_cart' i.product.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                                <a href="{% url 'cart:remove_from_cart' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                                {% else %}
                                                                                    <a href="{% url 'cart:decrement_cart' i.product.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                                <a href="{% url 'cart:remove_from_cart' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                                                    {% endif %}
                            </td>

                        </tr>

                    {% endfor %}
                </table>
            </div></div>
            <div class="col-4">
                <table class="table table-bordered">
                    <tr>
                        <th colspan="5">Check Out</th>
                    </tr>
                    <tr>Total = {{total}}</tr>
                </table>
                <a href="{% url 'cart:orderform' %}" class="btn btn-danger" >Place Order</a>
                <a href="{% url 'shop:allcat' %}" class="btn btn-danger">Continue Shopping</a>

        </div>
    </div>
</center>
{% endblock %}

templates/category.html
<! DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
    <img src="{% static 'images/123.png' %}" height="1000px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px; b">
    <h3 class="text-center fw-f=bold">Our Range Of Collections</h3>
    <p style="text-align:justify;line-height:2;">With over three decades of experience in the sales and distribution of glazed and cladding tiles, kitchen cabinets and units and bathroom fittings, the Kurikkal Group commenced operations in the district of Malappuram, in Kerala, before gradually expanding its presence to cover other locations. The Group has steadily maintained market leadership by focusing on uncompromising service quality and by adhering to the core values and principles that defined the vision of the founder.</p>
</div>

{% endblock %}

{% block category %}

<div class="container-fluid">
    <h1>COLLECTIONS</h1>
    <div class="row">
        {% for i in c %}
        <div class="col-md-4" style="max-width: 330px;">
            <div class="card">
                <img src="{{ i.image.url }}"  class="card-img-top" style="width:auto; height:250px; object-fit: fill;">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p class="card-text">Description: {{ i.desc }}</p>
                    <a href="{% url 'shop:product' i.name %}" class="btn btn-success d-block mx-auto">Products</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ p.image.url }}" style="height: 400px; width: 400px;" alt="{{ p.name }}">
        </div>
        <div class="col-md-6">
            <div class="choco">
                <h3>{{ p.name }}</h3>
                <p>{{ p.desc }}</p>
                <h5>stock<br>{{ p.stock }}</h5>
                <h3>Price  <br>₹ {{p.price}}</h3>
            </div>
            <div style="position: ; margin-bottom: 10px;">
                <a href="{% url 'cart:cart' p.name %}" class="btn btn-success d-block mx-auto">Add to cart</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>LOGIN>>></h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="Enter the username">
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter the password">
    </div>
    <div class="mb-3">
        <input type="submit" class="form-control">
    </div>
</form>
{% endblock %}

templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h3>Order Here</h3>

  <form method="POST" style="padding:20px;">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Address</label>
      <input type="text" class="form-control"  name="a" placeholder="Enter the address">
    </div>
    <div class="mb-3">
      <label class="form-label">Phone </label>
      <input type="number" class="form-control" name="ph" placeholder="Enter the phone number">
    </div>
    <div class="mb-3">
      <label class="form-label">Account Number</label>
      <input type="number" class="form-control" name="an" placeholder="Enter the account number">
    </div>
      <div>
      <input type="submit" class="form-control btn btn-danger">
    </div>
  </form>

</center>
{% endblock %}

templates/product.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<img src="{{ c.image.url }}" style="height: 400px; width: 100%">
<h3>{{ c.name }}</h3>
<p>{{ c.desc }}</p>
<div class="container-fluid" style="margin-bottom: 180px;">
  <div class="row justify-content-center">
    {% for i in p %}
      <div class="col-sm-4 mb-5">
        <div class="card">
          <img src="{{ i.image.url }}" height="200px" width="100%" class="card-img-top" alt="">
          <div class="card-body">
            <h5 class="card-title text-center">{{ i.name }}</h5>
            <p class="card-text text-center">{{ i.price }}</p>
            <a href="{% url 'shop:detail' i.name %} " class="btn btn-success d-block mx-auto">Details</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}
</body>
</html>

templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Register page</h1>
<form method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">User name</label>
    <input type="name" class="form-control" name="u">
<!--    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>-->
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="q">
  </div>
  <div class="mb-3">
    <label class="form-label">Conform Password</label>
    <input type="password" class="form-control" name="r" >
  </div>
    <div class="mb-3">
    <label class="form-label">First name</label>
    <input type="name" class="form-control" name="f">
  </div>
    <div class="mb-3">
    <label class="form-label">Last name</label>
    <input type="name" class="form-control" name="l">
  </div>
    <div class="mb-3">
    <label  class="form-label">Email</label>
    <input type="name" class="form-control" name="e">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid" style="margin-bottom: 180px;">
  <div class="row justify-content-center">
    {% if b %}
    {% for i in b %}
      <div class="col-sm-4 mb-5">
        <div class="card">
          <img src="{{ i.image.url }}" height="200px" width="100%" class="card-img-top" alt="">
          <div class="card-body">
            <h5 class="card-title text-center">{{ i.name }}</h5>
            <p class="card-text text-center">{{ i.price }}</p>
            <a href="{% url 'shop:detail' i.name %} " class="btn btn-success d-block mx-auto">Details</a>
          </div>
        </div>
      </div>
    {% endfor %}
    {% else %}
    <div><center>
      <h1>No Result Found</h1>
      </center>
    </div>
    {% endif %}
  </div>
</div>

{% endblock %}